=== terrikon/epamTask/EpamTask3Xml/src/epam/trainig/xmlTask/xmlFiles/Medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (x64) (http://www.altova.com) by dima (giraffe) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="medicine">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="drug" type="Drug" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Drug">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="pharm" type="xs:string"/>
			<xs:element name="group" type="Group"/>
			<xs:element name="analogs" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="versions" type="Version" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="country" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="Group">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PAINKILLERS"/>
			<xs:enumeration value="ANTIBIOTICS "/>
			<xs:enumeration value="VITAMINS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Version">
		<xs:sequence>
			<xs:element name="certificate">
				<xs:complexType>
					<xs:attribute name="number" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[a-zA-Z]{3}[a-zA-Z0-9_]{1,5}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="issuedate" type="xs:gYearMonth" use="required"/>
					<xs:attribute name="expdate" type="xs:gYearMonth" use="required"/>
					<xs:attribute name="reg_organization" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="package">
				<xs:complexType>
					<xs:attribute name="top" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="glass"/>
								<xs:enumeration value="plastic"/>
								<xs:enumeration value="paper"/>
								<xs:enumeration value="metal"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="amount" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:maxExclusive value="1000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="price" type="xs:double" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="dosage">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string" use="required"/>
					<xs:attribute name="period" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="1 time a day"/>
								<xs:enumeration value="2 times a day"/>
								<xs:enumeration value="3 times a day"/>
								<xs:enumeration value="4 times a day"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="number" type="Number" use="required"/>
		<xs:attribute name="consistence" type="Consistence" use="required"/>
		<xs:attribute name="pharm" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="Consistence">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TABLETS"/>
			<xs:enumeration value="CAPSULES"/>
			<xs:enumeration value="POWDERS"/>
			<xs:enumeration value="DROPS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Number">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{1,3}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== terrikon/epamTask/EpamTask3Xml/src/epam/trainig/xmlTask/xmlFiles/Medicine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<medicine xsi:noNamespaceSchemaLocation="Medicine.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<drug id="ID_1" country="USA">
		<name>Imet</name>
		<pharm>Google</pharm>
		<group>PAINKILLERS</group>
		<analogs>Ibuprofen</analogs>
		<analogs>Kitanov</analogs>
		<versions number="1" consistence="TABLETS" pharm="Google">
			<certificate number="aaa1b" issuedate="2008-07" expdate="2013-12" reg_organization="Rambler"/>
			<package top="glass" amount="150" price="58.60"/>
			<dosage value="3 drops" period="1 time a day"/>
		</versions>
		<versions number="2" consistence="CAPSULES" pharm="Epam">
			<certificate number="adf55" issuedate="2006-12" expdate="2014-10" reg_organization="Rambler"/>
			<package top="plastic" amount="30" price="62.80"/>
			<dosage value="2 capsules" period="2 times a day"/>
		</versions>
	</drug>
	<drug id="ID_4" country="Russia">
		<name>Eretromicin</name>
		<pharm>Yandex</pharm>
		<group>ANTIBIOTICS </group>
		<analogs>Tetraciclin</analogs>
		<analogs>Biocicline</analogs>
		<versions number="1" consistence="POWDERS" pharm="Yandex">
			<certificate number="fff123f" issuedate="2008-12" expdate="2018-06" reg_organization="Rambler"/>
			<package top="paper" amount="60" price="59.60"/>
			<dosage value="3 g" period="3 times a day"/>
		</versions>
		<versions number="2" consistence="DROPS" pharm="Epam">
			<certificate number="ggg34g" issuedate="2008-07" expdate="2015-04" reg_organization="Rambler"/>
			<package top="metal" amount="150" price="90.20"/>
			<dosage value="7 drops" period="4 times a day"/>
		</versions>
	</drug>
</medicine>
